// This is our single source of truth for puppies for sale.
// When you add a puppy here, it will automatically show up on the
// homepage preview AND the main "Available Puppies" page.

export const availablePups = [

  { 
    name: 'Daisy',
    slug: 'daisy',
    image: '/images/puppies/daisy.jpg',
    gallery: [
      '/images/puppies/daisy-1.jpg',
      '/images/puppies/daisy-2.jpg',
      '/images/puppies/daisy-3.jpg',
    ],
    price: 1200,
    status: 'Available', 
    gender: 'Female',
    breedType: 'American Bully',
    registry: 'ABKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Healthy and Vaccinated',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: '100% Domesticated & Potty Trained',
    description: 'Radiates pure cuteness and love, your heart wont stand a chance.'
  },

  { 
    name: 'Rocky',
    slug: 'rocky',
    image: '/images/puppies/rocky.jpg',
    gallery: [
      '/images/puppies/rocky-1.jpg',
      '/images/puppies/rocky-2.jpg',
      '/images/puppies/rocky-3.jpg',
    ],
    price: 1200,
    status: 'Available', 
    gender: 'Male',
    breedType: 'American Bully',
    registry: 'ABKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Healthy and Vaccinated',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: '100% Domesticated & Potty Trained',
    description: 'This puppy shows true love!! Always spreading positivity and happiness where ever he goes'
  },
  
  {
    name: 'Luna',
    slug: 'luna',
    image: '/images/puppies/luna.jpg',
    gallery: [
      '/images/puppies/luna-1.jpg',
      '/images/puppies/luna-2.jpg',
      '/images/puppies/luna-3.jpg',
    ],
    price: 1200,
    status: 'Available',
    gender: 'Female',
    breedType: 'American Bully',
    registry: 'AKC',
    hypoallergenic: 'yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Champion Bloodline',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: 'Crate Trained & Socialized',
    description: 'Female. Cream-colored. Sweet temperament and great with children.'
  },
  {
    name: 'Remus',
    slug: 'remus',
    image: '/images/puppies/remus.jpg',
    gallery: [
      '/images/puppies/remus-1.jpg',
      '/images/puppies/remus-2.jpg',
      '/images/puppies/remus-3.jpg',
    ],
    price: 1200,
    status: 'Available',
    gender: 'Female',
    breedType: 'American Bully',
    registry: 'AKC',
    hypoallergenic: 'No',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'On Site and Well-Trained',
    guarantee: '1 Year Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: 'Basic Commands & Housebroken',
    description: 'With loving heart and sweet nature, Remus is sure to steal your heart and you can’t even for a day regret having this wonderful pup 🐶'
  },
  {
    name: 'Cookie',
    slug: 'cookie',
    image: '/images/puppies/cookie.jpg',
    gallery: [
      '/images/puppies/cookie-1.jpg',
      '/images/puppies/cookie-2.jpg',
      '/images/puppies/cookie-3.jpg',
    ],
    price: 1200,
    status: 'Available',
    gender: 'Female',
    breedType: 'American Bully',
    registry: 'CKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Both Parents DNA Tested',
    guarantee: '1 Year Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: 'Potty Trained & Leash Ready',
    description: 'Humble puppy with a good personality doesn’t look for trouble and Always act as leader so adorable 🥹'
  },
  { 
    name: 'Apollo',
    slug: 'apollo',
    image: '/images/puppies/apollo.jpg',
    gallery: [
      '/images/puppies/apollo-1.jpg',
      '/images/puppies/apollo-2.jpg',
      '/images/puppies/apollo-3.jpg',
    ],
    price: 1200,
    status: 'Reserved', 
    gender: 'Male',
    breedType: 'American Bully',
    registry: 'ABKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Healthy and Vaccinated',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: '100% Domesticated & Potty Trained',
    description: 'Blue tri-color. Confident and playful with a champion pedigree. Loves cuddles and will melt your heart with his sweet, curious eyes'
  },

  { 
    name: 'Mark',
    slug: 'mark',
    image: '/images/puppies/mark.jpg',
    gallery: [
      '/images/puppies/mark-1.jpg',
      '/images/puppies/mark-2.jpg',
      '/images/puppies/mark-3.jpg',
    ],
    price: 1200,
    status: 'Available', 
    gender: 'Male',
    breedType: 'American Bully',
    registry: 'ABKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Healthy and Vaccinated',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: '100% Domesticated & Potty Trained',
    description: 'Very loving 🥰 plays a lot and very eager to make new friends along the way.'
  },

  { 
    name: 'Milo',
    slug: 'milo',
    image: '/images/puppies/milo.jpg',
    gallery: [
      '/images/puppies/milo-1.jpg',
      '/images/puppies/milo-2.jpg',
      '/images/puppies/milo-3.jpg',
    ],
    price: 1200,
    status: 'Available', 
    gender: 'Male',
    breedType: 'American Bully',
    registry: 'ABKC',
    hypoallergenic: 'Yes',
    vaccinations: 'Up to Date',
    shipping: 'Available',
    parentsOnSite: 'Healthy and Vaccinated',
    guarantee: '1 Year Genetic Health Guarantee',
    vetCertificate: 'Veterinary Health Exam Certificate',
    training: '100% Domesticated & Potty Trained',
    description: 'He is a cute guy with lots of energy and loves to be around people.'
  },
  

];

