// lib/reviewsData.ts

export interface Review {
  id: number;
  author: string;
  avatar: string;
  rating: number; // Allows for 3.5, 4, 5 stars
  platform: 'Google' | 'Trustpilot';
  date: string; // Using ISO string format for dates
  content: string;
  verified?: boolean; // For Trustpilot
}

// ✅ CORRECTED DATA: Dates now span the last 5 years, with the newest review being 2 days old.
export const reviewsData: Review[] = [
  {
    id: 31, // This will appear first when sorted by "Newest"
    author: 'Samuel Baker',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Samuel Baker',
    rating: 5,
    platform: 'Google',
    date: '2025-09-18T10:00:00Z', // 2 days ago
    content: 'Our puppy is a bundle of joy and has clearly been well-socialized. He got along with our older dog from day one. Fantastic breeder.',
  },
  {
    id: 1,
    author: 'Michael Thompson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Michael Thompson',
    rating: 5,
    platform: 'Google',
    date: '2025-09-15T08:30:00Z', // 5 days ago
    content: 'An absolutely seamless experience from start to finish. The team at 601 Bullies are true professionals. Our puppy, Zeus, is healthy, happy, and has the best temperament. You can tell these dogs are raised with love.',
  },
  {
    id: 34,
    author: 'Lauren Cook',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Lauren Cook',
    rating: 5,
    platform: 'Google',
    date: '2025-09-14T11:00:00Z',
    content: 'The entire experience felt very personal and not transactional at all. They really take the time to get to know you and make sure the puppy is going to a good home.',
  },
  {
    id: 35,
    author: 'Henry Morris',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Henry Morris',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-09-13T09:45:00Z',
    content: 'Our vet commented on the exceptional quality of our pup\'s bone structure and overall health. A testament to a great breeding program.',
    verified: true,
  },
  {
    id: 2,
    author: 'Jessica Chen',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jessica Chen',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-09-12T14:00:00Z',
    content: 'We were nervous about buying a puppy online, but 601 Bullies made us feel comfortable every step of the way. Constant updates, photos, and they answered all our questions. Our little Athena is a dream come true. Highly recommended!',
    verified: true,
  },
  {
    id: 36,
    author: 'Angela Peterson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Angela Peterson',
    rating: 5,
    platform: 'Google',
    date: '2025-09-11T20:00:00Z',
    content: 'The weekly video updates of our puppy were the highlight of our month! It was amazing to watch him grow before he came home.',
  },
  {
    id: 3,
    author: 'The Rodriguez Family',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=The Rodriguez Family',
    rating: 5,
    platform: 'Google',
    date: '2025-09-10T11:20:00Z',
    content: 'The quality of these American Bullies is second to none. Our vet was incredibly impressed with the puppy\'s health records and structure. A trustworthy breeder that genuinely cares about their dogs.',
  },
  {
    id: 37,
    author: 'Patrick Murphy',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Patrick Murphy',
    rating: 4,
    platform: 'Trustpilot',
    date: '2025-09-09T17:10:00Z',
    content: 'The dog is an absolute superstar, couldn\'t be happier with him. The only reason for 4 stars is that the delivery, which was scheduled for the morning, was delayed until late in the evening on the same day. The delivery driver kept in touch, so it wasn\'t a huge issue, just made for a long day of waiting. The pup arrived safe and happy.',
    verified: true,
  },
  {
    id: 4,
    author: 'David Lee',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=David Lee',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-09-08T18:45:00Z',
    content: 'Top-tier service and exceptional dogs. The entire process was transparent and professional. Our boy is a perfect example of the breed.',
    verified: true,
  },
  {
    id: 38,
    author: 'Katherine Bailey',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Katherine Bailey',
    rating: 5,
    platform: 'Google',
    date: '2025-09-07T13:00:00Z',
    content: 'A truly professional and ethical breeder. The health guarantee they provide is comprehensive and shows they stand behind their dogs 100%.',
  },
  {
    id: 39,
    author: 'Dennis Rivera',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Dennis Rivera',
    rating: 5,
    platform: 'Google',
    date: '2025-09-06T10:20:00Z',
    content: 'Our puppy is so intelligent! He learned basic commands within a week. Clearly comes from a great line of smart, trainable dogs.',
  },
  {
    id: 5,
    author: 'Emily White',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Emily White',
    rating: 5,
    platform: 'Google',
    date: '2025-09-05T09:00:00Z',
    content: 'We are so in love with our new family member. Thank you, 601 Bullies, for your dedication and for breeding such wonderful, well-socialized puppies.',
  },
  {
    id: 40,
    author: 'Janet Cooper',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Janet Cooper',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-09-04T16:50:00Z',
    content: 'The level of care and cleanliness at their facility (which they showed us via video call) was impressive. It’s clear the dogs are raised in a wonderful environment.',
    verified: true,
  },
  {
    id: 41,
    author: 'Walter Richardson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Walter Richardson',
    rating: 3,
    platform: 'Google',
    date: '2025-09-03T19:00:00Z',
    content: 'We had a lot of questions about the American Bully breed, and they answered every single one with patience and expertise. Great resource for new owners.',
  },
  {
    id: 21,
    author: 'Chris Evans',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Chris Evans',
    rating: 4,
    platform: 'Google',
    date: '2025-09-02T16:00:00Z',
    content: 'The puppy is amazing, absolutely perfect and healthy. My only issue was that communication was a bit slow at times; sometimes it took a day or two to get a response. I understand they are very busy, and in the end, everything worked out great. The quality of the dog is undeniable.',
  },
  {
    id: 42,
    author: 'Heather Cox',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Heather Cox',
    rating: 5,
    platform: 'Google',
    date: '2025-09-01T12:00:00Z',
    content: 'Our beautiful girl has brought so much love and laughter into our home. The entire process with 601 Bullies was a pleasure.',
  },
  {
    id: 22,
    author: 'Megan Turner',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Megan Turner',
    rating: 4,
    platform: 'Trustpilot',
    date: '2025-08-30T19:20:00Z',
    content: 'We love our new girl, she\'s beautiful. The shipping took a little longer than we initially expected. It was scheduled for a Tuesday but she ended up arriving Wednesday evening. The team was apologetic and kept us updated, and she arrived safely, which is all that matters.',
    verified: true,
  },
  {
    id: 43,
    author: 'Terry Howard',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Terry Howard',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-08-29T21:30:00Z',
    content: 'From the pedigree to the personality, everything about our puppy is top-notch. You get what you pay for, and this was worth every penny.',
    verified: true,
  },
  {
    id: 6,
    author: 'Brian Green',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Brian Green',
    rating: 5,
    platform: 'Google',
    date: '2025-08-28T12:10:00Z',
    content: 'The health guarantee and support they offer gave us peace of mind. A fantastic breeder that stands behind their program.',
  },
  {
    id: 44,
    author: 'Brenda Ward',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Brenda Ward',
    rating: 4,
    platform: 'Google',
    date: '2025-08-27T15:45:00Z',
    content: 'The puppy is perfect and the service was great overall. I just had to follow up once to get the tracking information for the shipping, as it wasn\'t sent automatically when I expected. A minor detail in an otherwise excellent process. The pup arrived safely and on the scheduled day.',
  },
  {
    id: 45,
    author: 'Adam Torres',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Adam Torres',
    rating: 5,
    platform: 'Google',
    date: '2025-08-26T10:00:00Z',
    content: 'The temperament of our pup is just incredible. So calm and loving. It\'s a testament to their careful breeding and early socialization.',
  },
  {
    id: 7,
    author: 'Sophia Martinez',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sophia Martinez',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-08-25T16:30:00Z',
    content: 'The shipping process was straightforward, and our puppy arrived safe and sound. The communication was excellent throughout.',
    verified: true,
  },
  {
    id: 46,
    author: 'Carlos Gomez',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Carlos Gomez',
    rating: 3.5,
    platform: 'Google',
    date: '2025-08-24T18:00:00Z',
    content: 'The puppy himself is a 5-star dog, no question. He\'s healthy and has a wonderful personality. However, the process was quite frustrating. We were given conflicting information about the pickup date from two different people, which caused us to reschedule our plans twice. It felt a bit disorganized. While we are ultimately happy with our dog, the communication process needs significant improvement.',
  },
  {
    id: 47,
    author: 'Russell Coleman',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Russell Coleman',
    rating: 5,
    platform: 'Google',
    date: '2025-08-23T11:50:00Z',
    content: 'Our bully has the most stunning coat and beautiful eyes. A real head-turner! And his personality is just as wonderful.',
  },
  {
    id: 8,
    author: 'Kevin Harris',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Kevin Harris',
    rating: 5,
    platform: 'Google',
    date: '2025-08-22T20:00:00Z',
    content: 'Our bully has the most amazing personality. Gentle with our kids but still has that confident bully look. Exactly what we wanted.',
  },
  {
    id: 48,
    author: 'Jacqueline Gray',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jacqueline Gray',
    rating: 5,
    platform: 'Google',
    date: '2025-08-21T09:10:00Z',
    content: 'They provided helpful tips on diet and training that have been invaluable for us as first-time bully owners. Great post-adoption support.',
  },
  {
    id: 23,
    author: 'Jordan Phillips',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jordan Phillips',
    rating: 4,
    platform: 'Google',
    date: '2025-08-20T10:30:00Z',
    content: 'The dog himself is 5 stars. He\'s healthy, well-behaved, and everything we wanted. The initial response to my inquiry took a few days which made me a bit anxious, but once we got talking, the process was smooth. They are clearly in high demand, so a little patience is needed. Worth it in the end.',
  },
  {
    id: 9,
    author: 'Olivia Clark',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Olivia Clark',
    rating: 5,
    platform: 'Google',
    date: '2025-08-19T13:25:00Z',
    content: 'Incredible experience. You can see the passion they have for the breed. Our puppy was already well on his way with potty training when he arrived!',
  },
  {
    id: 49,
    author: 'Carl James',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Carl James',
    rating: 4,
    platform: 'Trustpilot',
    date: '2025-08-18T18:00:00Z',
    content: 'The dog is 10/10 perfect. The only small snag was that the initial video call to see the puppies had to be rescheduled. They were very apologetic and it was quickly sorted out for the next day. Everything after that was flawless. Very happy overall.',
    verified: true,
  },
  {
    id: 50,
    author: 'Diana Watson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Diana Watson',
    rating: 5,
    platform: 'Google',
    date: '2025-07-17T16:00:00Z',
    content: 'An honest and transparent breeder. All health clearances for the parents were provided without us even having to ask. Highly trustworthy.',
  },
  {
    id: 51,
    author: 'Jonathan Brooks',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jonathan Brooks',
    rating: 5,
    platform: 'Google',
    date: '2025-06-16T12:45:00Z',
    content: 'Our puppy adjusted to our home so quickly. You can tell he was raised in a stable and loving environment from the very beginning.',
  },
  {
    id: 10,
    author: 'James Walker',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=James Walker',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-05-15T10:55:00Z',
    content: 'If you want a high-quality American Bully from a breeder you can trust, look no further. 601 Bullies is the real deal.',
    verified: true,
  },
  {
    id: 52,
    author: 'Sara Kelly',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sara Kelly',
    rating: 5,
    platform: 'Trustpilot',
    date: '2025-04-14T15:00:00Z',
    content: 'The entire litter of puppies looked healthy and happy in the videos. It was hard to choose just one! We are thrilled with our choice.',
    verified: true,
  },
  {
    id: 53,
    author: 'Alice Johnson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Alice Johnson',
    rating: 3.5,
    platform: 'Trustpilot',
    date: '2025-03-13T14:00:00Z',
    content: 'Let me be clear: the puppy is wonderful and we love her. But the process was a headache. The shipping was delayed twice, pushing delivery back by almost 3 days. We were also sent the wrong brand of starter food, which led to some minor stomach upset for the pup. For the price, I expected the logistics to be much smoother. The quality of the dog is the only reason this isn\'t a lower score.',
    verified: true,
  },
  {
    id: 11,
    author: 'Chloe Robinson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Chloe Robinson',
    rating: 5,
    platform: 'Google',
    date: '2025-02-11T19:15:00Z',
    content: 'The most beautiful puppy I have ever seen. The pictures didn\'t do her justice. Healthy, active, and so smart!',
  },
  {
    id: 54,
    author: 'Christina Price',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Christina Price',
    rating: 5,
    platform: 'Google',
    date: '2025-01-12T08:00:00Z',
    content: 'We are so grateful for the care and effort they put into their dogs. It truly shows in the quality and temperament of our puppy.',
  },
  {
    id: 55,
    author: 'Aaron Bennett',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Aaron Bennett',
    rating: 4,
    platform: 'Trustpilot',
    date: '2024-12-10T19:20:00Z',
    content: 'The dog is fantastic, a truly beautiful animal. The shipping company they used was professional, but they gave us a 4-hour delivery window and arrived right at the end of it, which made for a bit of a long wait. Not the breeder\'s fault directly, and the main thing is he arrived safely.',
    verified: true,
  },
  {
    id: 12,
    author: 'Thomas Allen',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Thomas Allen',
    rating: 5,
    platform: 'Google',
    date: '2024-11-07T14:40:00Z',
    content: 'Professionalism at its best. They provided all the paperwork, vet records, and a puppy starter pack. Made the whole process easy.',
  },
  {
    id: 56,
    author: 'Rebecca Wood',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Rebecca Wood',
    rating: 5,
    platform: 'Google',
    date: '2024-10-09T14:00:00Z',
    content: 'They have a real passion for the American Bully breed and it shines through in everything they do. I wouldn\'t go anywhere else.',
  },
  {
    id: 57,
    author: 'Jose Perry',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jose Perry',
    rating: 5,
    platform: 'Google',
    date: '2024-09-08T11:15:00Z',
    content: 'Our puppy has a clean bill of health from our vet and a heart of gold. The perfect combination. Thank you 601 Bullies!',
  },
  {
    id: 13,
    author: 'Grace Hall',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Grace Hall',
    rating: 5,
    platform: 'Trustpilot',
    date: '2024-08-02T11:00:00Z',
    content: 'The payment plan option was a huge help for our family. It made getting our dream dog possible. Thank you for being so accommodating!',
    verified: true,
  },
  {
    id: 58,
    author: 'Shirley Hughes',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Shirley Hughes',
    rating: 5,
    platform: 'Trustpilot',
    date: '2024-07-06T17:00:00Z',
    content: 'The process of reserving our puppy and making payments was simple and secure. Very professional from a business standpoint.',
    verified: true,
  },
  {
    id: 24,
    author: 'Victoria Adams',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Victoria Adams',
    rating: 4,
    platform: 'Google',
    date: '2024-06-05T22:00:00Z',
    content: 'Fantastic puppy, really top quality. The only reason for 4 stars instead of 5 is that the final travel crate was different from the one shown in the prep photos, which caused a minor confusion at pickup. Not a big deal at all, and the puppy was safe and happy. Just a small detail.',
  },
  {
    id: 59,
    author: 'Scott Washington',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Scott Washington',
    rating: 5,
    platform: 'Google',
    date: '2024-05-04T13:30:00Z',
    content: 'Our pup is confident, curious, and incredibly loving. He has been a joy to train. A testament to his great start in life.',
  },
  {
    id: 60,
    author: 'Laura Simmons',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Laura Simmons',
    rating: 5,
    platform: 'Google',
    date: '2024-04-03T09:45:00Z',
    content: 'We were looking for a bully with a specific look and temperament, and they matched us with the perfect puppy. They really listen to what you\'re looking for.',
  },
  {
    id: 61,
    author: 'Steven Foster',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Steven Foster',
    rating: 4,
    platform: 'Trustpilot',
    date: '2024-03-01T18:50:00Z',
    content: 'Our puppy is a gem and we are so happy. The response to my final payment confirmation email was delayed by a day, which caused a little stress, but they were very busy with a new litter. They apologized and confirmed everything was set for shipping, which went smoothly. A small communication blip in a great experience.',
    verified: true,
  },
  {
    id: 62,
    author: 'Maria Gonzales',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Maria Gonzales',
    rating: 5,
    platform: 'Google',
    date: '2024-02-28T12:00:00Z',
    content: 'They raise incredible dogs. Period. The quality is evident in every way. We are thrilled to be part of the 601 Bullies family.',
  },
  {
    id: 14,
    author: 'Daniel Young',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Daniel Young',
    rating: 5,
    platform: 'Google',
    date: '2024-01-29T17:20:00Z',
    content: 'Our bully is the star of the neighborhood. Everyone comments on his stunning looks and friendly nature. We couldn\'t be happier.',
  },
  {
    id: 63,
    author: 'Paul Bryant',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Paul Bryant',
    rating: 5,
    platform: 'Google',
    date: '2023-12-20T10:00:00Z',
    content: 'Our puppy gets along wonderfully with our cats and children. He has such a gentle and patient nature. Couldn\'t ask for a better fit for our family.',
  },
  {
    id: 64,
    author: 'Kevin Mitchell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Kevin Mitchell',
    rating: 3.5,
    platform: 'Google',
    date: '2023-11-18T18:30:00Z',
    content: 'The dog is great, very healthy and happy. The administrative side of things was a real struggle, though. The registration paperwork had the wrong birthdate, and it took over a month and three follow-up emails to get the corrected documents sent to us. It was a frustrating process that overshadowed an otherwise good experience. Love the dog, but the paperwork headache was significant.',
  },
  {
    id: 15,
    author: 'Zoe King',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Zoe King',
    rating: 5,
    platform: 'Google',
    date: '2023-10-25T09:30:00Z',
    content: 'The health and structure of these dogs are phenomenal. A breeder who truly prioritizes the well-being of their animals.',
  },
  {
    id: 65,
    author: 'Joshua Jenkins',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Joshua Jenkins',
    rating: 5,
    platform: 'Google',
    date: '2023-09-27T19:00:00Z',
    content: 'The entire journey, from first contact to puppy pickup, was a five-star experience. True professionals who love what they do.',
  },
  {
    id: 16,
    author: 'Matthew Wright',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Matthew Wright',
    rating: 5,
    platform: 'Trustpilot',
    date: '2023-08-21T21:00:00Z',
    content: 'I was kept informed throughout the entire process. The weekly pup-dates were something my whole family looked forward to!',
    verified: true,
  },
  {
    id: 66,
    author: 'Amanda Ross',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Amanda Ross',
    rating: 5,
    platform: 'Google',
    date: '2023-07-26T14:10:00Z',
    content: 'We are constantly stopped on walks by people admiring our beautiful dog. His structure and coloring are just perfect.',
  },
  {
    id: 67,
    author: 'Jason Powell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Jason Powell',
    rating: 4,
    platform: 'Trustpilot',
    date: '2023-06-24T11:30:00Z',
    content: 'The puppy is absolutely flawless and has settled in so well. The only minor issue was that shipping, which was planned for Friday, got pushed to Saturday morning due to a flight scheduling issue with the pet carrier. The breeder was communicative about it, but it did change our weekend plans. He arrived safe and sound, which is the main thing.',
    verified: true,
  },
  {
    id: 17,
    author: 'Lily Scott',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Lily Scott',
    rating: 5,
    platform: 'Google',
    date: '2023-05-18T12:00:00Z',
    content: 'Absolutely worth the wait. Our puppy is everything we hoped for and more. A perfect addition to our family.',
  },
  {
    id: 68,
    author: 'Michelle Long',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Michelle Long',
    rating: 5,
    platform: 'Google',
    date: '2023-04-23T09:00:00Z',
    content: 'The advice they gave on socializing our puppy was spot on. He is confident and friendly with new people and dogs. A great foundation.',
  },
  {
    id: 25,
    author: 'Ben Campbell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Ben Campbell',
    rating: 4,
    platform: 'Trustpilot',
    date: '2023-03-15T13:00:00Z',
    content: 'The entire experience was very positive, and the dog is perfect. The only small issue was a delay in receiving the official ABKC paperwork by mail; it arrived about two weeks after the puppy. They were responsive when I followed up. I would still recommend them to anyone.',
    verified: true,
  },
  {
    id: 18,
    author: 'Andrew Nelson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Andrew Nelson',
    rating: 5,
    platform: 'Google',
    date: '2023-02-14T15:10:00Z',
    content: 'The knowledge and expertise of the 601 Bullies team is impressive. They were able to answer all my questions about the breed and care.',
  },
  {
    id: 69,
    author: 'Gary Patterson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Gary Patterson',
    rating: 5,
    platform: 'Google',
    date: '2023-01-22T15:00:00Z',
    content: 'They delivered exactly what they promised: a healthy, beautiful, well-tempered American Bully. We are extremely satisfied customers.',
  },
  {
    id: 70,
    author: 'Sandra Hughes',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Sandra Hughes',
    rating: 5,
    platform: 'Trustpilot',
    date: '2022-12-20T17:45:00Z',
    content: 'I was impressed by their commitment to the breed standard while prioritizing health and temperament above all else. A truly responsible breeder.',
    verified: true,
  },
  {
    id: 19,
    author: 'Ella Carter',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Ella Carter',
    rating: 5,
    platform: 'Trustpilot',
    date: '2022-11-10T18:45:00Z',
    content: 'Our puppy arrived clean, healthy, and happy. The shipping was handled very professionally. A very positive experience.',
    verified: true,
  },
  {
    id: 71,
    author: 'Mark Russell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Mark Russell',
    rating: 5,
    platform: 'Google',
    date: '2022-10-19T10:20:00Z',
    content: 'Our family is complete now, thanks to our wonderful pup from 601 Bullies. The joy he brings is immeasurable. Worth every bit of the investment.',
  },
  {
    id: 26,
    author: 'Hannah Perez',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Hannah Perez',
    rating: 5,
    platform: 'Google',
    date: '2022-09-08T16:45:00Z',
    content: 'The best of the best. From the moment we inquired, we were treated like family. The care and attention to detail is unmatched.',
  },
  {
    id: 72,
    author: 'Elizabeth Griffin',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Elizabeth Griffin',
    rating: 4,
    platform: 'Google',
    date: '2022-08-17T12:00:00Z',
    content: 'We adore our puppy! She is healthy and has a great personality. The communication was a little slow in the beginning, likely due to how busy they are. Once we put our deposit down, the updates were much more frequent. Overall, we are very happy and would recommend them.',
  },
  {
    id: 27,
    author: 'Joshua Edwards',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Joshua Edwards',
    rating: 5,
    platform: 'Trustpilot',
    date: '2022-07-01T11:30:00Z',
    content: 'An investment in quality. Our vet continues to be impressed by our pup\'s health and structure at every check-up. 601 Bullies sets the standard.',
    verified: true,
  },
  {
    id: 73,
    author: 'George Butler',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=George Butler',
    rating: 5,
    platform: 'Trustpilot',
    date: '2022-05-16T09:30:00Z',
    content: 'The whole process was a class act. From the detailed information on their website to the final handover, everything was handled with professionalism.',
    verified: true,
  },
  {
    id: 20,
    author: 'Ryan Mitchell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Ryan Mitchell',
    rating: 5,
    platform: 'Google',
    date: '2022-04-05T10:00:00Z',
    content: 'The best decision we ever made. Our bully has brought so much joy into our home. Thank you 601 Bullies!',
  },
  {
    id: 28,
    author: 'Ashley Collins',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Ashley Collins',
    rating: 5,
    platform: 'Google',
    date: '2021-11-28T09:00:00Z',
    content: 'They patiently answered my million questions and made sure I was ready for a bully. The post-adoption support has been amazing too.',
  },
  {
    id: 74,
    author: 'Susan Henderson',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Susan Henderson',
    rating: 5,
    platform: 'Google',
    date: '2021-07-13T14:00:00Z',
    content: 'They breed for temperament, and it shows. Our bully is the sweetest, most gentle dog we\'ve ever owned. He\'s amazing with our grandchildren.',
  },
  {
    id: 29,
    author: 'Justin Stewart',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Justin Stewart',
    rating: 5,
    platform: 'Google',
    date: '2021-02-22T14:50:00Z',
    content: 'Our puppy has the most loving and goofy personality. He fits into our active lifestyle perfectly. Couldn\'t have asked for a better dog.',
  },
  {
    id: 75,
    author: 'Larry Bell',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Larry Bell',
    rating: 5,
    platform: 'Google',
    date: '2020-10-12T16:15:00Z',
    content: 'I\'m a repeat customer, and my second experience was just as fantastic as the first. Consistent quality and service. 601 Bullies is the only breeder I\'ll ever work with.',
  },
  {
    id: 30,
    author: 'Nicole Sanchez',
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=Nicole Sanchez',
    rating: 5,
    platform: 'Trustpilot',
    date: '2020-09-25T18:00:00Z',
    content: 'The entire experience exceeded our expectations. Professional, honest, and they breed incredible dogs. We will be back for our next one!',
    verified: true,
  },
];